services:
  db:
    image: postgres:13
    # PostgreSQLコンテナの環境変数を設定
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ホストマシンのポート 5432 をコンテナのポート 5432 にマッピング
    ports:
      - '5432:5432'
    # ホストマシン上の名前付きボリューム db-data をPostgreSQLコンテナの /var/lib/postgresql/data ディレクトリにマウントする
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      # コマンドシェルで　pg_isready コマンドを使用して、データベースが準備完了であることをチェック
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - '8080:8080'
    # web サービスは db サービスがヘルシーであると判断されるまで待機
    depends_on:
      db:
        condition: service_healthy

# コンテナとホストマシン間でデータを共有するための設定
volumes:
  db-data:
